server {
    listen 8099;
    server_name _;
    root /usr/share/nginx/html;
    gzip off;
    client_max_body_size 0;

    location = /leaderboard.json {
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ \.zip$ {
        add_header Content-Type application/zip;
        add_header Content-Disposition 'attachment';
    }
}
